// Code generated by zero-rpc. DO NOT EDIT.

package server

import (
	"context"

	"{{.Module}}/logic"
	"{{.Module}}/proto"
	"{{.Module}}/svc"
)

type {{.Service.Name}}Server struct {
	proto.{{.Service.Name}}Server
	svc  *svc.Svc
}

func New{{.Service.Name}}Server(svc *svc.Svc) *{{.Service.Name}}Server {
	return &{{.Service.Name}}Server{
		svc: svc,
	}
}
{{range .Service.Methods}}
{{.Comment}}
func (server {{$.Service.Name}}Server) {{.Name}}(ctx context.Context, input *proto.{{.Param}}) (*proto.{{.Return}}, error) {
	return logic.{{.Name}}(&svc.Session{
		Svc: *server.svc,
		Ctx:    ctx,
	}, input)
}
{{end}}
