// Code generated by zero-rpc. DO NOT EDIT.

package server

import (
	"context"

	"{{.Package}}/logic"
	"{{.Package}}/proto"
	"{{.Package}}/svc"
)

type {{.Service.Name}}Server struct {
	proto.SensitiveServer
	svc  *svc.Svc
}

func NewSensitiveServer(svc *svc.Svc) *SensitiveServer {
	return &SensitiveServer{
		svc: svc,
	}
}
{{range .Service.Methods}}
{{.Comment}}
func (server {{$.Service.Name}}Server) {{.Name}}(ctx context.Context, input *proto.{{.Param}}) (*proto.{{.Return}}, error) {
	return logic.{{.Name}}(&svc.Session{
		Svc: *server.svc,
		Ctx:    ctx,
	}, input)
}
{{end}}
