// Code generated by zero-rpc. DO NOT EDIT.

package client

import (
	"context"
	"{{.Module}}/proto"

	"github.com/zeromicro/go-zero/core/discov"
	"github.com/zeromicro/go-zero/zrpc"
)

type {{.Service.Name}}Client struct {
	rpcClient zrpc.Client
	client    proto.{{.Service.Name}}Client
}

func New{{.Service.Name}}Client(etcHosts []string) (*{{.Service.Name}}Client, error) {
	rpcClient, err := zrpc.NewClient(zrpc.RpcClientConf{
		Etcd: discov.EtcdConf{
			Hosts: etcHosts,
			Key:   "{{.Package}}.rpc",
		},
		Timeout: 2000,
		Middlewares: zrpc.ClientMiddlewaresConf{
			Trace: true,
			Duration: true,
			Prometheus: true,
			Breaker: true,
			Timeout: true,
		},
	})
	if err != nil {
		return nil, err
	}
	return &{{.Service.Name}}Client{
		rpcClient: rpcClient,
		client: proto.New{{.Service.Name}}Client(rpcClient.Conn()),
	}, nil
}
{{range .Service.Methods}}
{{.Comment}}
func (c *{{$.Service.Name}}Client) {{.Name}}(ctx context.Context, input *proto.{{.Param}}) (*proto.{{.Return}}, error) {
	return c.client.{{.Name}}(ctx, input)
}
{{end}}

func (c *{{.Service.Name}}Client)Close() {
	c.rpcClient.Conn().Close()
}